### ISSUE TITLE
#Story Command Not Functioning

### ISSUE THREAD

**Issue by Novel-Idea** [ktrzonkowski/soulbot#6]
#story command not functioning, no matter the input.

For example:
```@Philomena #story 386671``` sent through Discord. (This command got a proper story response in the Q&B server).

Running Node soulbot.js response:
```(node:4244) DeprecationWarning: TextChannel#sendMessage: use TextChannel#send instead```

**Comment by ktrzonkowski** [comment]
Do you have a FiMFiction API Key in the config.json file, like so:

```
{
  "clientId": "<BOT TOKEN... I need to rename this key>",
  "mainChat": "general-chat",
  "announceNewUsers": true,
  "greetNewUsersPersonally": true,
  "fimfictionAccessKey": "<FIMFICTION API KEY>"
}
```

**Comment by AzureNightLight** [comment]
DeprecationWarnings mean that due to the changes in in the libraries, the function may not work properly in the future. It should be impossible for DeprecationWarning to be the issue itself.
The segment in the story function implies that it is attempting to find a FiMFiction Access Key in the config.
`"Authorization": "Bearer " + bot.config.fimfictionAccessKey`
This also means that the sample config file needs updating, as it is not there.

**Comment by ktrzonkowski** [comment]
Updated the sample config file.
